resolver: lts-5.16
packages:
- '.'
- location:
    git: https://github.com/ekmett/recursion-schemes.git
    commit: cf42f2ace35ca09a8ab489538e9493f8333bc0ec
extra-deps: []
flags: {}
extra-package-dbs: []